name: Build Release Candidate
on: 
  workflow_dispatch:
    branches: 
      - release_candidate

env:
  FILENAME_PREFIX: RTK_Surveyor_Firmware_
  RC_PREFIX: RC-
  VERSION_MAJOR: 3
  VERSION_MINOR: 1
  POINTPERFECT_TOKEN: ${{ secrets.POINTPERFECT_TOKEN }}

jobs:
  build:
    
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Start config file
        run: arduino-cli config init --additional-urls "https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json"

      - name: Update index
        run: arduino-cli core update-index

      #We limit the ESP32 core to v2.0.2
      - name: Install platform
        run: arduino-cli core install esp32:esp32@2.0.2

      - name: Enable external libs
        run: arduino-cli config set library.enable_unsafe_install true

      - name: Get Libraries
        run: arduino-cli lib install --git-url 
          https://github.com/fbiego/ESP32Time.git
          https://github.com/me-no-dev/ESPAsyncWebServer.git 
          https://github.com/me-no-dev/AsyncTCP.git 
          https://github.com/JChristensen/JC_Button.git 
          https://github.com/greiman/SdFat.git 
          https://github.com/sparkfun/SparkFun_u-blox_GNSS_v3.git
          https://github.com/sparkfun/SparkFun_MAX1704x_Fuel_Gauge_Arduino_Library.git 
          https://github.com/sparkfun/SparkFun_Qwiic_OLED_Arduino_Library.git 
          https://github.com/sparkfun/SparkFun_LIS2DH12_Arduino_Library.git 
          https://github.com/bblanchon/ArduinoJson.git 
          https://github.com/knolleary/pubsubclient.git
          https://github.com/avinabmalla/ESP32_BleSerial.git
          https://github.com/nseidle/ESP32-OTA-Pull.git

      #Incorporate ESP-Now patch into v2.0.4 core: https://github.com/espressif/arduino-esp32/pull/7044/files
      # - name: Patch ESP32 Core
      #   run: |
      #     cd Firmware/RTK_Surveyor/Patch/
      #     cp WiFiGeneric.cpp /home/runner/.arduino15/packages/esp32/hardware/esp32/2.0.4/libraries/WiFi/src/WiFiGeneric.cpp

      - name: Compile Sketch
        run: arduino-cli compile --fqbn "esp32:esp32:esp32":DebugLevel=debug ./Firmware/RTK_Surveyor/RTK_Surveyor.ino
          --build-property build.partitions=partitions
          --build-property upload.maximum_size=3145728 
          --build-property "compiler.cpp.extra_flags=\"-DPOINTPERFECT_TOKEN=$POINTPERFECT_TOKEN\""
          --export-binaries

      - name: Get current date
        id: date
        run: echo "date=$(date +'%b_%d_%Y')" >> $GITHUB_OUTPUT

      - name: Get current date
        id: dateNoScores
        run: echo "dateNoScores=$(date +'%b %d %Y')" >> $GITHUB_OUTPUT

      - name: Rename binary
        run: |
          cd Firmware/RTK_Surveyor
          cd build
          cd esp32.esp32.esp32
          mv RTK_Surveyor.ino.bin ${{ env.FILENAME_PREFIX }}${{ env.RC_PREFIX }}${{ steps.date.outputs.date }}.bin

      - name: Upload binary to action
        uses: actions/upload-artifact@v3
        with: 
          name: ${{ env.FILENAME_PREFIX }}${{ env.RC_PREFIX }}${{ steps.date.outputs.date }}
          path: ./Firmware/RTK_Surveyor/build/esp32.esp32.esp32/${{ env.FILENAME_PREFIX }}${{ env.RC_PREFIX }}${{ steps.date.outputs.date }}.bin 
          
      - name: Push binary to Binaries Repo
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_GITHUB_RTK_FILE_TOKEN }}
        with:
          source_file: ./Firmware/RTK_Surveyor/build/esp32.esp32.esp32/${{ env.FILENAME_PREFIX }}${{ env.RC_PREFIX }}${{ steps.date.outputs.date }}.bin
          destination_repo: 'sparkfun/SparkFun_RTK_Firmware_Binaries'
          destination_folder: ''
          user_email: 'nathan@sparkfun.com'
          user_name: 'nseidle'
          commit_message: 'Github Action - Updating Binary ${{ steps.dateNoScores.outputs.dateNoScores }}'

      - name: Update JSON File
        uses: "DamianReeves/write-file-action@master"
        with:
          path: RTK-RC-Firmware.json
          write-mode: overwrite
          contents: |
            {"Configurations": [{"Version":"${{ env.VERSION_MAJOR }}.${{ env.VERSION_MINOR }}-${{ steps.dateNoScores.outputs.dateNoScores }}", "URL":"https://raw.githubusercontent.com/sparkfun/SparkFun_RTK_Firmware_Binaries/main/${{ env.FILENAME_PREFIX }}${{ env.RC_PREFIX }}${{ steps.date.outputs.date }}.bin"}]}

      - name: Push JSON to Binaries Repo
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_GITHUB_RTK_FILE_TOKEN }}
        with:
          source_file: RTK-RC-Firmware.json
          destination_repo: 'sparkfun/SparkFun_RTK_Firmware_Binaries'
          destination_folder: ''
          user_email: 'nathan@sparkfun.com'
          user_name: 'nseidle'
          commit_message: 'Github Action - Updating JSON ${{ steps.dateNoScores.outputs.dateNoScores }}'